version: '1.0'
services:
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY_DB}
      POSTGRES_DB: ${POSTGRES_INVENTORY_DB}
    ports:
      - ${POSTGRES_PORT_INVENTORY_DB}:5432
    # volumes:
    #   - ./database/inventory-db/data:/var/lib/postgresql/data
  billing-db:
    image: postgres
    container_name: billing-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BILLING_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BILLING_DB}
      POSTGRES_DB: ${POSTGRES_BILLING_DB}
    ports:
      - ${POSTGRES_PORT_BILLING_DB}:5432
    # volumes:
    #   - ./database/billing-db/data:/var/lib/postgresql/data
