version: '1.0'
services:
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY_DB}
      POSTGRES_DB: ${POSTGRES_INVENTORY_DB}
    ports:
      - ${POSTGRES_PORT_INVENTORY_DB}:5432