version: '1.0'
services:
  billing-db:
    image: postgres
    container_name: billing-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BILLING_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BILLING_DB}
      POSTGRES_DB: ${POSTGRES_BILLING_DB}
    ports:
      - ${POSTGRES_PORT_BILLING_DB}:5432
    # volumes:
    #   - ./database/billing-db/data:/var/lib/postgresql/data
  order-queue:
    image: rabbitmq:3-management
    container_name: order-queue
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


